from typing import List, Dict, Any
from .utils import ActionResult, ensure_pkg, run, write_file
import shlex
import os

# Default AIDE configuration for CIS compliance
DEFAULT_AIDE_CONF = """# AIDE configuration file for CIS compliance
# Generated by CIS hardening scripts

/bin R+b+sha256
/sbin R+b+sha256
/usr/bin R+b+sha256
/usr/sbin R+b+sha256
/lib R+b+sha256
/lib64 R+b+sha256
/usr/lib R+b+sha256
/usr/lib64 R+b+sha256

/etc R+b+sha256
!/etc/mtab
!/etc/.*~

/root R+b+sha256

# Check configuration files
/boot R+b+sha256
!/boot/grub2/grubenv

# Exclude some directories
!/proc
!/sys
!/dev
!/run
!/var/run
!/var/log/aide
"""

def apply(cfg: Dict[str,Any], dry_run: bool, profile: str) -> List[ActionResult]:
    results = []
    
    # Ensure AIDE package is installed
    ensure_pkg(["aide"], dry_run, results, "AIDE-1", "Install AIDE package")
    
    # Ensure AIDE configuration exists
    control_id = "AIDE-CONFIG"
    title = "Ensure AIDE configuration file exists"
    changed = False
    ok = True
    notes = ""
    commands = []
    files = ["/etc/aide.conf"]
    
    aide_conf = "/etc/aide.conf"
    if not os.path.exists(aide_conf):
        if not dry_run:
            changed, note = write_file(aide_conf, DEFAULT_AIDE_CONF, mode=0o644, dry_run=dry_run)
            notes = f"Created default AIDE configuration: {note}"
            ok = True
        else:
            notes = "DRY-RUN: Would create default AIDE configuration"
            commands.append(f"cat > {aide_conf} << 'EOF'\n{DEFAULT_AIDE_CONF}EOF")
    else:
        notes = "AIDE configuration file already exists"
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=ok,
        notes=notes,
        commands=commands,
        files=files
    ))
    
    # Initialize AIDE database if configured
    init = bool(cfg.get("initialize_if_missing", False))
    if not init:
        results.append(ActionResult(
            "AIDE-2",
            "AIDE initialization (skipped by config)",
            False,
            True,
            notes="Set aide.initialize_if_missing=true to initialize"
        ))
        return results
    
    cmd = ["bash", "-lc", "aide --init 2>&1 && mv -f /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz 2>/dev/null || true"]
    if dry_run:
        results.append(ActionResult(
            "AIDE-2",
            "Initialize AIDE database",
            False,
            True,
            notes="DRY-RUN: would run " + shlex.join(cmd),
            commands=[shlex.join(cmd)]
        ))
        return results
    
    cp = run(cmd)
    ok = cp.returncode == 0 or os.path.exists("/var/lib/aide/aide.db.gz") or os.path.exists("/var/lib/aide/aide.db")
    notes = (cp.stdout + cp.stderr).strip() if cp.stdout or cp.stderr else "AIDE database initialized"
    
    results.append(ActionResult(
        "AIDE-2",
        "Initialize AIDE database",
        True,
        ok,
        notes=notes,
        commands=[shlex.join(cmd)]
    ))
    
    return results
