from typing import List, Dict, Any
from .utils import ActionResult, ensure_pkg, run, write_file
import shlex
import os

# Default AIDE configuration for CIS compliance
DEFAULT_AIDE_CONF = """# AIDE configuration file for CIS compliance
# Generated by CIS hardening scripts

/bin R+b+sha256
/sbin R+b+sha256
/usr/bin R+b+sha256
/usr/sbin R+b+sha256
/lib R+b+sha256
/lib64 R+b+sha256
/usr/lib R+b+sha256
/usr/lib64 R+b+sha256

/etc R+b+sha256
!/etc/mtab
!/etc/.*~

/root R+b+sha256

# Check configuration files
/boot R+b+sha256
!/boot/grub2/grubenv

# Exclude some directories
!/proc
!/sys
!/dev
!/run
!/var/run
!/var/log/aide
"""

# AIDE daily check cron script
AIDE_CRON_SCRIPT = """#!/bin/bash
# AIDE Daily Integrity Check
# Generated by CIS hardening scripts

AIDE_BIN="/usr/sbin/aide"
AIDE_LOG="/var/log/aide/aide-check.log"
MAIL_TO="{email}"
HOSTNAME=$(hostname)

# Create log directory if needed
mkdir -p /var/log/aide

# Run AIDE check
$AIDE_BIN --check > "$AIDE_LOG" 2>&1
RESULT=$?

# Log the result
if [ $RESULT -eq 0 ]; then
    echo "$(date): AIDE check passed - no changes detected" >> /var/log/aide/aide-summary.log
else
    echo "$(date): AIDE check detected changes (exit code: $RESULT)" >> /var/log/aide/aide-summary.log
    
    # Send email alert if configured
    if [ -n "$MAIL_TO" ] && command -v mail &> /dev/null; then
        mail -s "AIDE Alert: File integrity changes detected on $HOSTNAME" "$MAIL_TO" < "$AIDE_LOG"
    fi
fi

exit $RESULT
"""

def apply(cfg: Dict[str,Any], dry_run: bool, profile: str) -> List[ActionResult]:
    results = []
    
    # Ensure AIDE package is installed
    ensure_pkg(["aide"], dry_run, results, "AIDE-1", "Install AIDE package")
    
    # Ensure AIDE configuration exists
    control_id = "AIDE-CONFIG"
    title = "Ensure AIDE configuration file exists"
    changed = False
    ok = True
    notes = ""
    commands = []
    files = ["/etc/aide.conf"]
    
    aide_conf = "/etc/aide.conf"
    if not os.path.exists(aide_conf):
        if not dry_run:
            changed, note = write_file(aide_conf, DEFAULT_AIDE_CONF, mode=0o644, dry_run=dry_run)
            notes = f"Created default AIDE configuration: {note}"
            ok = True
        else:
            notes = "DRY-RUN: Would create default AIDE configuration"
            commands.append(f"cat > {aide_conf} << 'EOF'\n{DEFAULT_AIDE_CONF}EOF")
    else:
        notes = "AIDE configuration file already exists"
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=ok,
        notes=notes,
        commands=commands,
        files=files
    ))
    
    # Initialize AIDE database if configured
    init = bool(cfg.get("initialize_if_missing", False))
    db_exists = os.path.exists("/var/lib/aide/aide.db.gz") or os.path.exists("/var/lib/aide/aide.db")
    
    if not init and not db_exists:
        results.append(ActionResult(
            "AIDE-2",
            "AIDE initialization (skipped by config)",
            False,
            True,
            notes="Set aide.initialize_if_missing=true to initialize; No database found"
        ))
    elif db_exists and not init:
        results.append(ActionResult(
            "AIDE-2",
            "AIDE database exists",
            False,
            True,
            notes="AIDE database already initialized"
        ))
    else:
        cmd = ["bash", "-lc", "aide --init 2>&1 && mv -f /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz 2>/dev/null || true"]
        if dry_run:
            results.append(ActionResult(
                "AIDE-2",
                "Initialize AIDE database",
                False,
                True,
                notes="DRY-RUN: would run " + shlex.join(cmd),
                commands=[shlex.join(cmd)]
            ))
        else:
            cp = run(cmd)
            ok = cp.returncode == 0 or os.path.exists("/var/lib/aide/aide.db.gz") or os.path.exists("/var/lib/aide/aide.db")
            notes = (cp.stdout + cp.stderr).strip() if cp.stdout or cp.stderr else "AIDE database initialized"
            
            results.append(ActionResult(
                "AIDE-2",
                "Initialize AIDE database",
                True,
                ok,
                notes=notes,
                commands=[shlex.join(cmd)]
            ))
    
    # Control: Schedule daily AIDE check via cron
    control_id = "AIDE-3"
    title = "Schedule daily AIDE integrity check"
    changed = False
    ok = True
    notes = ""
    commands = []
    files = []
    
    schedule_daily = cfg.get("schedule_daily_check", True)
    email_alerts = cfg.get("email_alerts", False)
    alert_email = cfg.get("alert_email", "root@localhost")
    
    if schedule_daily:
        cron_script_path = "/etc/cron.daily/aide-check"
        cron_content = AIDE_CRON_SCRIPT.format(email=alert_email if email_alerts else "")
        
        script_exists = os.path.exists(cron_script_path)
        
        if not dry_run:
            # Create log directory
            os.makedirs("/var/log/aide", exist_ok=True)
            
            # Write cron script
            c, n = write_file(cron_script_path, cron_content, mode=0o755, dry_run=dry_run)
            if c:
                changed = True
                notes = f"Created daily AIDE check cron job: {cron_script_path}"
            else:
                notes = "Daily AIDE check cron job already exists"
            
            files.append(cron_script_path)
        else:
            notes = f"DRY-RUN: Would create {cron_script_path}"
            changed = not script_exists
        
        if email_alerts:
            notes += f"; Email alerts enabled to {alert_email}"
    else:
        notes = "Daily AIDE check scheduling disabled in configuration"
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=ok,
        notes=notes,
        commands=commands,
        files=files
    ))
    
    # Control: Configure systemd timer/service for AIDE (alternative to cron)
    control_id = "AIDE-3b"
    title = "Configure AIDE systemd timer and service"
    changed = False
    ok = True
    notes = ""
    
    use_systemd_timer = cfg.get("use_systemd_timer", True)
    
    if use_systemd_timer:
        # Create aidecheck.service
        service_content = """[Unit]
Description=AIDE File Integrity Check
After=local-fs.target

[Service]
Type=oneshot
ExecStart=/usr/sbin/aide --check
Nice=19
IOSchedulingClass=best-effort
IOSchedulingPriority=7
"""
        
        # Create aidecheck.timer
        timer_content = """[Unit]
Description=Daily AIDE File Integrity Check Timer

[Timer]
OnCalendar=daily
RandomizedDelaySec=3600
Persistent=true

[Install]
WantedBy=timers.target
"""
        
        service_path = "/etc/systemd/system/aidecheck.service"
        timer_path = "/etc/systemd/system/aidecheck.timer"
        
        if not dry_run:
            c1, n1 = write_file(service_path, service_content, mode=0o644, dry_run=dry_run)
            c2, n2 = write_file(timer_path, timer_content, mode=0o644, dry_run=dry_run)
            
            if c1 or c2:
                changed = True
                # Reload systemd and enable timer
                run(["systemctl", "daemon-reload"])
                run(["systemctl", "enable", "--now", "aidecheck.timer"])
                notes = "Created and enabled AIDE systemd timer"
            else:
                notes = "AIDE systemd timer already configured"
        else:
            notes = "DRY-RUN: Would create AIDE systemd timer and service"
            changed = True
        
        results.append(ActionResult(
            id=control_id,
            title=title,
            changed=changed,
            ok=ok,
            notes=notes,
            files=[service_path, timer_path] if use_systemd_timer else []
        ))
    
    # Control: Configure AIDE email alerts
    control_id = "AIDE-4"
    title = "Configure AIDE email alerts"
    changed = False
    ok = True
    
    if email_alerts:
        # Verify mail command is available
        mail_available = os.path.exists("/usr/bin/mail") or os.path.exists("/bin/mail")
        if mail_available:
            notes = f"Email alerts configured to {alert_email}"
        else:
            notes = f"Email alerts configured but 'mail' command not found; install mailx package"
            ok = True  # Informational, not a hard failure
    else:
        notes = "Email alerts disabled; set aide.email_alerts=true to enable"
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=ok,
        notes=notes,
        files=[]
    ))
    
    # Control: Configure AIDE to check audit tools integrity
    control_id = "AIDE-5"
    title = "Configure AIDE to monitor audit tools integrity"
    changed = False
    ok = True
    notes = ""
    
    aide_conf = "/etc/aide.conf"
    audit_tools_check = """
# CIS Requirement: Monitor audit tool integrity
/sbin/auditctl p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/auditd p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/ausearch p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/aureport p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/autrace p+i+n+u+g+s+b+acl+xattrs+sha512
/sbin/augenrules p+i+n+u+g+s+b+acl+xattrs+sha512
"""
    
    try:
        if os.path.exists(aide_conf):
            with open(aide_conf, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()
            
            if "/sbin/auditctl" not in content:
                if not dry_run:
                    with open(aide_conf, "a", encoding="utf-8") as f:
                        f.write(audit_tools_check)
                    changed = True
                    notes = "Added audit tools integrity checking to AIDE configuration"
                else:
                    notes = "DRY-RUN: Would add audit tools to AIDE configuration"
                    changed = True
            else:
                notes = "Audit tools already configured in AIDE"
        else:
            notes = "AIDE configuration file not found"
    except Exception as e:
        ok = False
        notes = f"Error: {str(e)}"
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=ok,
        notes=notes,
        files=[aide_conf]
    ))
    
    return results
