from typing import List, Dict, Any
from .utils import ActionResult, run
import os, shlex

def apply(cfg: Dict[str,Any], dry_run: bool, profile: str):
    dropin="/etc/ssh/sshd_config.d/99-cis-hardening.conf"
    permit_root=str(cfg.get("permit_root_login","no"))
    password_auth=str(cfg.get("password_authentication","no"))
    x11=str(cfg.get("x11_forwarding","no"))
    max_auth=int(cfg.get("max_auth_tries",4))
    grace=int(cfg.get("login_grace_time",60))
    cai=int(cfg.get("client_alive_interval",300))
    cacm=int(cfg.get("client_alive_count_max",0))
    atf=str(cfg.get("allow_tcp_forwarding","no"))
    aaf=str(cfg.get("allow_agent_forwarding","no"))
    ciphers=str(cfg.get("ciphers","")).strip()
    macs=str(cfg.get("macs","")).strip()
    kex=str(cfg.get("kex_algorithms","")).strip()

    lines=[
      "# Generated by cis hardening scripts",
      f"PermitRootLogin {permit_root}",
      f"PasswordAuthentication {password_auth}",
      f"X11Forwarding {x11}",
      f"MaxAuthTries {max_auth}",
      f"LoginGraceTime {grace}",
      f"ClientAliveInterval {cai}",
      f"ClientAliveCountMax {cacm}",
      f"AllowTcpForwarding {atf}",
      f"AllowAgentForwarding {aaf}",
      "UsePAM yes",
      "PermitEmptyPasswords no",
      "IgnoreRhosts yes",
      "HostbasedAuthentication no",
      "PermitUserEnvironment no",
      "LogLevel INFO",
    ]
    if ciphers: lines.append(f"Ciphers {ciphers}")
    if macs: lines.append(f"MACs {macs}")
    if kex: lines.append(f"KexAlgorithms {kex}")
    content="\n".join(lines)+"\n"
    changed=True
    if os.path.exists(dropin):
        with open(dropin,"r",encoding="utf-8",errors="ignore") as f:
            changed = (f.read()!=content)
    cmds=[["bash","-lc", f"mkdir -p /etc/ssh/sshd_config.d && cat > {shlex.quote(dropin)} <<'EOF'\n{content}EOF\nchmod 600 {shlex.quote(dropin)}"],
          ["sshd","-t"],
          ["systemctl","restart","sshd"]]
    if dry_run:
        return [ActionResult("SSH-1","Harden SSH daemon configuration", changed, True,
                             notes="DRY-RUN: would write drop-in, validate (sshd -t), restart sshd",
                             commands=[shlex.join(c) for c in cmds], files=[dropin])]
    out=[]; ok=True
    for c in cmds:
        cp=run(c); out.append((cp.stdout+cp.stderr).strip()); ok = ok and (cp.returncode==0)
        if c[:2]==["sshd","-t"] and cp.returncode!=0:
            ok=False; break
    return [ActionResult("SSH-1","Harden SSH daemon configuration", True if changed else False, ok,
                         notes="\n".join(o for o in out if o),
                         commands=[shlex.join(c) for c in cmds], files=[dropin])]
