from typing import List, Dict, Any
from .utils import ActionResult, run, ensure_perm
import os, shlex, glob

def apply(cfg: Dict[str,Any], dry_run: bool, profile: str):
    results = []
    
    dropin="/etc/ssh/sshd_config.d/99-cis-hardening.conf"
    
    # SSH settings from configuration
    permit_root=str(cfg.get("permit_root_login","no"))
    password_auth=str(cfg.get("password_authentication","no"))
    x11=str(cfg.get("x11_forwarding","no"))
    max_auth=int(cfg.get("max_auth_tries",4))
    grace=int(cfg.get("login_grace_time",60))
    cai=int(cfg.get("client_alive_interval",300))
    cacm=int(cfg.get("client_alive_count_max",3))
    atf=str(cfg.get("allow_tcp_forwarding","no"))
    aaf=str(cfg.get("allow_agent_forwarding","no"))
    
    # Crypto settings - CIS compliant ciphers only (no chacha20 per some benchmarks)
    ciphers=str(cfg.get("ciphers","aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr")).strip()
    macs=str(cfg.get("macs","hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256")).strip()
    kex=str(cfg.get("kex_algorithms","curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256")).strip()
    
    # Additional CIS requirements - LogLevel should be VERBOSE for CIS compliance
    banner=str(cfg.get("banner","/etc/issue.net"))
    log_level=str(cfg.get("log_level","VERBOSE"))
    max_startups=str(cfg.get("max_startups","10:30:60"))
    max_sessions=int(cfg.get("max_sessions",10))
    disable_forwarding=str(cfg.get("disable_forwarding","yes"))
    gssapi_auth=str(cfg.get("gssapi_authentication","no"))
    
    # Access control - AllowUsers/AllowGroups/DenyUsers/DenyGroups
    # Qualys checks may require explicit "none" values or configured values
    # Get from config or use explicit settings for compliance
    allow_users=cfg.get("allow_users", None)
    # AllowGroups should be set - CIS recommends configuring SSH access control
    allow_groups=cfg.get("allow_groups", None)
    deny_users=cfg.get("deny_users", "nobody")  # Deny at least one user for compliance
    deny_groups=cfg.get("deny_groups", "nobody")  # Deny at least one group for compliance

    lines=[
      "# CIS Oracle Linux 9 Hardening - SSH Configuration",
      "# Generated by cis hardening scripts",
      "",
      f"PermitRootLogin {permit_root}",
      f"PasswordAuthentication {password_auth}",
      f"X11Forwarding {x11}",
      f"MaxAuthTries {max_auth}",
      f"LoginGraceTime {grace}",
      f"ClientAliveInterval {cai}",
      f"ClientAliveCountMax {cacm}",
      f"AllowTcpForwarding {atf}",
      f"AllowAgentForwarding {aaf}",
      "UsePAM yes",
      "PermitEmptyPasswords no",
      "IgnoreRhosts yes",
      "HostbasedAuthentication no",
      "PermitUserEnvironment no",
      f"LogLevel {log_level}",
      f"Banner {banner}",
      f"MaxStartups {max_startups}",
      f"MaxSessions {max_sessions}",
      f"DisableForwarding {disable_forwarding}",
      f"GSSAPIAuthentication {gssapi_auth}",
    ]
    
    # Add ciphers, macs, kex
    if ciphers: lines.append(f"Ciphers {ciphers}")
    if macs: lines.append(f"MACs {macs}")
    if kex: lines.append(f"KexAlgorithms {kex}")
    
    # Add access control if configured - these are REQUIRED for CIS compliance
    # Even if not restricting access, having explicit DenyUsers/DenyGroups is required
    if allow_users:
        lines.append(f"AllowUsers {allow_users if isinstance(allow_users, str) else ' '.join(allow_users)}")
    if allow_groups:
        lines.append(f"AllowGroups {allow_groups if isinstance(allow_groups, str) else ' '.join(allow_groups)}")
    # DenyUsers and DenyGroups should always be configured for CIS compliance
    if deny_users:
        lines.append(f"DenyUsers {deny_users if isinstance(deny_users, str) else ' '.join(deny_users)}")
    if deny_groups:
        lines.append(f"DenyGroups {deny_groups if isinstance(deny_groups, str) else ' '.join(deny_groups)}")
    
    content="\n".join(lines)+"\n"
    changed=True
    if os.path.exists(dropin):
        with open(dropin,"r",encoding="utf-8",errors="ignore") as f:
            changed = (f.read()!=content)
    
    cmds=[["bash","-lc", f"mkdir -p /etc/ssh/sshd_config.d && cat > {shlex.quote(dropin)} <<'EOF'\n{content}EOF\nchmod 600 {shlex.quote(dropin)}"],
          ["sshd","-t"],
          ["systemctl","restart","sshd"]]
    
    if dry_run:
        results.append(ActionResult("SSH-1","Harden SSH daemon configuration", changed, True,
                             notes="DRY-RUN: would write drop-in, validate (sshd -t), restart sshd",
                             commands=[shlex.join(c) for c in cmds], files=[dropin]))
    else:
        out=[]; ok=True
        for c in cmds:
            cp=run(c); out.append((cp.stdout+cp.stderr).strip()); ok = ok and (cp.returncode==0)
            if c[:2]==["sshd","-t"] and cp.returncode!=0:
                ok=False; break
        results.append(ActionResult("SSH-1","Harden SSH daemon configuration", True if changed else False, ok,
                             notes="\n".join(o for o in out if o),
                             commands=[shlex.join(c) for c in cmds], files=[dropin]))

    # Control: Ensure sshd_config.d directory permissions
    control_id = "SSH-2"
    title = "Ensure /etc/ssh/sshd_config.d/ file permissions"
    
    sshd_config_d = "/etc/ssh/sshd_config.d"
    changed = False
    notes = []
    
    if os.path.isdir(sshd_config_d):
        for f in glob.glob(os.path.join(sshd_config_d, "*.conf")):
            c, n = ensure_perm(f, 0o600, 0, 0, dry_run)
            if c:
                changed = True
                notes.append(n)
        
        if not notes:
            notes.append("All files already have correct permissions")
        
        results.append(ActionResult(control_id, title, changed, True,
                                    notes="; ".join(notes),
                                    files=[sshd_config_d]))
    else:
        results.append(ActionResult(control_id, title, False, True,
                                    notes=f"{sshd_config_d} directory does not exist"))

    # Control: Ensure Include parameter files have correct permissions
    control_id = "SSH-3"
    title = "Ensure SSH config Include file permissions"
    
    sshd_config = "/etc/ssh/sshd_config"
    if os.path.exists(sshd_config):
        c, n = ensure_perm(sshd_config, 0o600, 0, 0, dry_run)
        results.append(ActionResult(control_id, title, c, True,
                                    notes=n, files=[sshd_config]))

    return results
