"""
Sudo Configuration Hardening
CIS Reference: 5.3.x series - Privilege Escalation Configuration
"""
from typing import List, Dict, Any
from .utils import ActionResult, write_file, run
import os
import re

def apply(cfg: Dict[str, Any], dry_run: bool, profile: str) -> List[ActionResult]:
    """
    Apply sudo hardening:
    - Configure use_pty for terminal allocation
    - Configure detailed logging (logfile, log_host, log_session)
    - Set timestamp_timeout for sudo session
    - Configure privilege escalation alerts
    """
    results = []
    
    # Build comprehensive sudoers drop-in configuration
    use_pty = cfg.get("use_pty", True)
    logfile = cfg.get("logfile", "/var/log/sudo.log")
    log_host = cfg.get("log_host", True)
    log_year = cfg.get("log_year", True)
    log_input = cfg.get("log_input", True)
    log_output = cfg.get("log_output", True)
    timestamp_timeout = cfg.get("timestamp_timeout", 5)
    requiretty = cfg.get("requiretty", True)
    env_reset = cfg.get("env_reset", True)
    
    # Build configuration lines
    lines = [
        "# CIS Oracle Linux 9 Hardening - Sudo Configuration",
        "# Generated by cis hardening scripts",
        "",
    ]
    
    if use_pty:
        lines.append("Defaults use_pty")
    
    if logfile:
        lines.append(f'Defaults logfile="{logfile}"')
    
    if log_host:
        lines.append("Defaults log_host")
    
    if log_year:
        lines.append("Defaults log_year")
    
    if log_input:
        lines.append("Defaults log_input")
    
    if log_output:
        lines.append("Defaults log_output")
    
    if timestamp_timeout is not None:
        lines.append(f"Defaults timestamp_timeout={timestamp_timeout}")
    
    if requiretty:
        lines.append("Defaults requiretty")
    
    if env_reset:
        lines.append("Defaults env_reset")
        lines.append('Defaults env_keep = "COLORS DISPLAY HOSTNAME HISTSIZE KDEDIR LS_COLORS"')
        lines.append('Defaults env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"')
        lines.append('Defaults env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"')
        lines.append('Defaults env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"')
        lines.append('Defaults env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"')
    
    # Secure path
    lines.append('Defaults secure_path = "/sbin:/bin:/usr/sbin:/usr/bin"')
    
    # Add empty line at end
    lines.append("")
    
    content = "\n".join(lines)
    dropin_file = "/etc/sudoers.d/99-cis-hardening"
    
    # Control: Configure sudo settings
    control_id = "SUDO-1"
    title = "Configure sudo with use_pty, logging, and security settings"
    
    changed, note = write_file(dropin_file, content, mode=0o440, dry_run=dry_run)
    
    # Validate sudoers syntax if not dry-run
    if not dry_run and changed:
        check_result = run(["visudo", "-c", "-f", dropin_file])
        if check_result.returncode != 0:
            # Revert if invalid
            os.remove(dropin_file)
            results.append(ActionResult(
                id=control_id,
                title=title,
                changed=False,
                ok=False,
                notes=f"Sudoers syntax check failed: {check_result.stderr}",
                commands=["visudo -c -f /etc/sudoers.d/99-cis-hardening"],
                files=[dropin_file]
            ))
            return results
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=True,
        notes=note,
        commands=["visudo -c -f /etc/sudoers.d/99-cis-hardening"],
        files=[dropin_file]
    ))
    
    # Control: Ensure sudo log file exists with proper permissions
    control_id = "SUDO-2"
    title = "Ensure sudo log file exists with proper permissions"
    changed = False
    ok = True
    notes = ""
    
    if logfile and not dry_run:
        if not os.path.exists(logfile):
            # Create the log file
            with open(logfile, "a") as f:
                pass
            os.chmod(logfile, 0o600)
            os.chown(logfile, 0, 0)
            changed = True
            notes = f"Created {logfile} with mode 0600"
        else:
            # Ensure proper permissions
            current_mode = os.stat(logfile).st_mode & 0o777
            if current_mode != 0o600:
                os.chmod(logfile, 0o600)
                changed = True
                notes = f"Fixed permissions on {logfile} from {oct(current_mode)} to 0600"
            else:
                notes = f"{logfile} already has correct permissions"
    else:
        notes = "DRY-RUN: would create/verify sudo log file" if dry_run else "No logfile configured"
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=ok,
        notes=notes,
        files=[logfile] if logfile else []
    ))
    
    # Control: Ensure sudo commands use pty
    control_id = "SUDO-3"
    title = "Verify sudo use_pty is enabled"
    
    # Already configured in SUDO-1, just verify
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=False,
        ok=use_pty,
        notes="use_pty enabled in sudoers configuration" if use_pty else "use_pty disabled (not recommended)",
        files=[dropin_file]
    ))
    
    # Control: Restrict access to su command
    control_id = "SUDO-4"
    title = "Restrict access to the su command"
    changed = False
    ok = True
    notes = ""
    
    restrict_su = cfg.get("restrict_su", True)
    su_group = cfg.get("su_group", "wheel")
    
    if restrict_su:
        pam_su = "/etc/pam.d/su"
        
        try:
            if os.path.exists(pam_su):
                with open(pam_su, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
                
                # Check if pam_wheel.so is already enabled
                # The line should be: auth required pam_wheel.so use_uid group=wheel
                wheel_pattern = r'^auth\s+required\s+pam_wheel\.so\s+use_uid'
                
                if not re.search(wheel_pattern, content, re.MULTILINE):
                    # Need to add or uncomment the line
                    wheel_line = f"auth            required        pam_wheel.so use_uid group={su_group}\n"
                    
                    # Check if there's a commented version
                    if "#auth" in content and "pam_wheel.so" in content:
                        # Uncomment and modify
                        new_content = re.sub(
                            r'^#\s*auth\s+required\s+pam_wheel\.so.*$',
                            f"auth            required        pam_wheel.so use_uid group={su_group}",
                            content,
                            flags=re.MULTILINE
                        )
                    else:
                        # Add after the first auth line
                        new_content = re.sub(
                            r'^(auth\s+\S+\s+pam_rootok\.so.*)$',
                            r'\1\n' + wheel_line.rstrip(),
                            content,
                            count=1,
                            flags=re.MULTILINE
                        )
                    
                    if new_content != content:
                        if not dry_run:
                            with open(pam_su, "w", encoding="utf-8") as f:
                                f.write(new_content)
                            changed = True
                            notes = f"Enabled pam_wheel.so in {pam_su} for group {su_group}"
                        else:
                            notes = f"DRY-RUN: Would enable pam_wheel.so for group {su_group}"
                            changed = True
                else:
                    notes = f"pam_wheel.so already configured in {pam_su}"
            else:
                notes = f"{pam_su} not found"
                ok = False
        except Exception as e:
            notes = f"Error: {str(e)}"
            ok = False
    else:
        notes = "su restriction disabled in configuration"
    
    results.append(ActionResult(
        id=control_id,
        title=title,
        changed=changed,
        ok=ok,
        notes=notes,
        files=["/etc/pam.d/su"]
    ))
    
    return results