from typing import List, Dict, Any
from .utils import ActionResult, run
import os, shlex

L1 = {
 "kernel.randomize_va_space": "2",
 "net.ipv4.ip_forward": "0",
 "net.ipv4.conf.all.send_redirects": "0",
 "net.ipv4.conf.default.send_redirects": "0",
 "net.ipv4.conf.all.accept_source_route": "0",
 "net.ipv4.conf.default.accept_source_route": "0",
 "net.ipv4.conf.all.accept_redirects": "0",
 "net.ipv4.conf.default.accept_redirects": "0",
 "net.ipv4.conf.all.secure_redirects": "0",
 "net.ipv4.conf.default.secure_redirects": "0",
 "net.ipv4.conf.all.log_martians": "1",
 "net.ipv4.conf.default.log_martians": "1",
 "net.ipv4.icmp_echo_ignore_broadcasts": "1",
 "net.ipv4.icmp_ignore_bogus_error_responses": "1",
 "net.ipv4.conf.all.rp_filter": "1",
 "net.ipv4.conf.default.rp_filter": "1",
 "net.ipv4.tcp_syncookies": "1",
 "net.ipv6.conf.all.accept_ra": "0",
 "net.ipv6.conf.default.accept_ra": "0",
 "net.ipv6.conf.all.accept_redirects": "0",
 "net.ipv6.conf.default.accept_redirects": "0",
}

L2 = {
 "kernel.kptr_restrict": "2",
 "kernel.dmesg_restrict": "1",
 "kernel.yama.ptrace_scope": "1",
 "fs.protected_hardlinks": "1",
 "fs.protected_symlinks": "1",
 "net.ipv4.tcp_rfc1337": "1",
}

def _content(kv: dict) -> str:
    lines=["# Generated by cis hardening scripts"]
    for k,v in sorted(kv.items()):
        lines.append(f"{k} = {v}")
    return "\n".join(lines)+"\n"

def apply(cfg: Dict[str,Any], dry_run: bool, profile: str):
    kv=dict(L1)
    if profile.startswith("l2"):
        kv.update(L2)
    path="/etc/sysctl.d/99-cis-hardening.conf"
    content=_content(kv)
    changed=True
    if os.path.exists(path):
        with open(path,"r",encoding="utf-8",errors="ignore") as f:
            changed = (f.read()!=content)
    cmds=[["bash","-lc", f"cat > {shlex.quote(path)} <<'EOF'\n{content}EOF\nchmod 644 {shlex.quote(path)}"],
          ["sysctl","--system"]]
    if dry_run:
        return [ActionResult("SYSCTL-1","Apply CIS sysctl hardening", changed, True,
                             notes="DRY-RUN: would write sysctl conf and run sysctl --system",
                             commands=[shlex.join(c) for c in cmds], files=[path])]
    out=[]; ok=True
    for c in cmds:
        cp=run(c); out.append((cp.stdout+cp.stderr).strip()); ok = ok and (cp.returncode==0)
    return [ActionResult("SYSCTL-1","Apply CIS sysctl hardening", True if changed else False, ok,
                         notes="\n".join(o for o in out if o),
                         commands=[shlex.join(c) for c in cmds], files=[path])]
